version: '3.4'
services:
  app:
    image: aws-project-service
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
    container_name: aws-project-service-app
    ports:
      - 9090:9090
    depends_on:
      - localstack
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
      - "8080:8080"