version: '3.4'
services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=sqs,dynamodb # a list of desired services you want to use.
      - DEFAULT_REGION=us-east-1 # This is the region where your localstack mocks to be running
      - DATA_DIR=/tmp/localstack/data
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
#    networks:
#      testing_net:
#        ipv4_address: 172.28.1.2
#  app:
#    image: luizimcpi/aws-project-service
#    environment:
#      - SPRING_PROFILES_ACTIVE=local
#      - AWS_ACCESS_KEY_ID=foo
#      - AWS_SECRET_ACCESS_KEY=bar
#    container_name: aws-project-service-app
#    ports:
#      - 9090:9090
#    depends_on:
#      - localstack
#    restart: always
#    networks:
#      testing_net:
#        ipv4_address: 172.28.1.1

#networks:
#  testing_net:
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.28.0.0/16